import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { MessageModule } from 'primeng/message';
import { TextareaModule } from 'primeng/textarea';
import { Adr, AgentTask, Domain, Plan, Workflow } from '../../core/plan.schema';
import { PlanSchemaService, STUB_MARKER } from '../../core/plan-schema.service';
import { ProjectStore } from '../../core/project.store';

type AddFormKind = 'adr' | 'workflow' | 'task' | 'domain:manual';
type DomainKind = 'adr' | 'workflow' | 'task' | 'domain';

interface NewAdrDraft {
  id: string;
  title: string;
  context: string;
  decision: string;
}

interface NewWorkflowDraft {
  id: string;
  name: string;
  description: string;
}

interface NewTaskDraft {
  id: string;
  title: string;
  description: string;
  acceptanceCriteria: string;
  fileHints: string;
}

interface NewDomainManualDraft {
  name: string;
  description: string;
}

@Component({
  selector: 'app-plan-fields-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, ButtonModule, InputTextModule, MessageModule, TextareaModule],
  template: `
    @if (!draft()) {
      <p class="empty-hint">Generate a plan to view and edit its fields here.</p>
    } @else {
      <fieldset class="fields-editor" [disabled]="readonly()">

        <!-- Application Idea -->
        <section class="editor-section">
          <h3 class="section-title">Application Idea</h3>
          <div class="field-grid">
            <div class="field full-width">
              <label class="field-label">Original idea</label>
              <textarea
                pTextarea
                class="w-full"
                rows="5"
                [value]="ideaDraft()"
                (blur)="onUserIdeaChange($any($event.target).value)"
                [readonly]="readonly()"
              ></textarea>
            </div>
          </div>
        </section>

        <!-- Meta -->
        <section class="editor-section">
          <h3 class="section-title">Plan Summary</h3>
            <div class="field-grid">
              <div class="field">
                <label class="field-label">Title</label>
                <input
                  pInputText
                  class="w-full"
                  [value]="draft()!.meta.title"
                  (blur)="onMetaChange('title', $any($event.target).value)"
                />
              </div>
              <div class="field full-width">
                <label class="field-label">Summary</label>
                <textarea
                  pTextarea
                  class="w-full"
                  rows="5"
                  [value]="draft()!.meta.summary"
                  (blur)="onMetaChange('summary', $any($event.target).value)"
                ></textarea>
              </div>
            </div>
        </section>

        <!-- System Overview -->
        <section class="editor-section">
          <h3 class="section-title">System Overview</h3>
            <div class="field-grid">
              <div class="field full-width">
                <label class="field-label">Purpose</label>
                <textarea
                  pTextarea
                  class="w-full"
                  rows="5"
                  [value]="draft()!.systemOverview.purpose"
                  (blur)="onOverviewChange('purpose', $any($event.target).value)"
                ></textarea>
              </div>
              <div class="field full-width">
                <label class="field-label">Context</label>
                <textarea
                  pTextarea
                  class="w-full"
                  rows="5"
                  [value]="draft()!.systemOverview.context"
                  (blur)="onOverviewChange('context', $any($event.target).value)"
                ></textarea>
              </div>
            </div>
        </section>

        <!-- Domains -->
        @if (draft()!.domains.length > 0) {
          <section class="editor-section">
            <h3 class="section-title">
              Domains
              <span class="count-badge">{{ draft()!.domains.length }}</span>
            </h3>
            <div class="list-grid domains-list">
              @for (domain of draft()!.domains; track domain.id; let i = $index) {
                <div class="list-card">
                  @if (isDomainStubbed(domain.id)) {
                    <p-message
                      severity="warn"
                      styleClass="w-full"
                      text="This domain was not generated by the LLM. Fill it in manually."
                    />
                  }
                    <input
                      pInputText
                      class="w-full card-input"
                      [value]="domain.name"
                      (blur)="onDomainChange(i, 'name', $any($event.target).value)"
                      placeholder="Domain name"
                    />
                    <textarea
                      pTextarea
                      class="w-full"
                      rows="3"
                      [value]="domain.description"
                      (blur)="onDomainChange(i, 'description', $any($event.target).value)"
                      placeholder="Description"
                    ></textarea>
                    <div class="card-actions">
                      <p-button
                        label="Remove"
                        severity="danger"
                        [outlined]="true"
                        size="small"
                        (onClick)="removeItem('domain', domain.id)"
                      />
                    </div>
                </div>
              }
            </div>
              <div class="section-footer">
                <p-button
                  label="Add Domain"
                  icon="pi pi-plus"
                  severity="secondary"
                  [outlined]="true"
                  (onClick)="toggleAddForm('domain:manual')"
                />
              </div>
              @if (expandedAddForm() === 'domain:manual') {
                <form class="add-form" (ngSubmit)="saveDomainManual()">
                  <h4 class="add-form-title">New domain</h4>
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Domain name (e.g. Orders)"
                    [(ngModel)]="newDomainManual.name"
                    name="domainManualName"
                  />
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="3"
                    placeholder="Description"
                    [(ngModel)]="newDomainManual.description"
                    name="domainManualDescription"
                  ></textarea>
                  <div class="add-form-actions">
                    <p-button
                      label="Cancel"
                      severity="secondary"
                      [text]="true"
                      type="button"
                      (onClick)="cancelAdd()"
                    />
                    <p-button
                      label="Save Domain"
                      icon="pi pi-check"
                      [disabled]="!canSaveDomainManual()"
                      type="button"
                      (onClick)="saveDomainManual()"
                    />
                  </div>
                </form>
              }
          </section>
        }

        <!-- ADRs -->
        @if (draft()!.adrs.length > 0) {
          <section class="editor-section">
            <h3 class="section-title">
              Architecture Decision Records
              <span class="count-badge">{{ draft()!.adrs.length }}</span>
            </h3>
            <div class="list-grid">
              @for (adr of draft()!.adrs; track adr.id; let i = $index) {
                <div class="list-card">
                    <input
                      pInputText
                      class="w-full card-input"
                      [value]="adr.title"
                      (blur)="onAdrChange(i, 'title', $any($event.target).value)"
                      placeholder="ADR title"
                    />
                    <textarea
                      pTextarea
                      class="w-full"
                      rows="5"
                      [value]="adr.decision"
                      (blur)="onAdrChange(i, 'decision', $any($event.target).value)"
                      placeholder="Decision"
                    ></textarea>
                    <div class="card-actions">
                      <p-button
                        label="Remove"
                        severity="danger"
                        [outlined]="true"
                        size="small"
                        (onClick)="removeItem('adr', adr.id)"
                      />
                    </div>
                </div>
              }
            </div>
              <div class="section-footer">
                <p-button
                  label="Add ADR"
                  icon="pi pi-plus"
                  severity="secondary"
                  [outlined]="true"
                  (onClick)="toggleAddForm('adr')"
                />
              </div>
              @if (expandedAddForm() === 'adr') {
                <form class="add-form">
                  <h4 class="add-form-title">New ADR</h4>
                  <input
                    pInputText
                    class="w-full"
                    placeholder="ADR id (e.g. adr-002)"
                    [(ngModel)]="newAdr.id"
                    name="adrId"
                  />
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Title"
                    [(ngModel)]="newAdr.title"
                    name="adrTitle"
                  />
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="3"
                    placeholder="Context"
                    [(ngModel)]="newAdr.context"
                    name="adrContext"
                  ></textarea>
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="3"
                    placeholder="Decision"
                    [(ngModel)]="newAdr.decision"
                    name="adrDecision"
                  ></textarea>
                  <div class="add-form-actions">
                    <p-button
                      label="Cancel"
                      severity="secondary"
                      [text]="true"
                      type="button"
                      (onClick)="cancelAdd()"
                    />
                    <p-button
                      label="Save ADR"
                      icon="pi pi-check"
                      type="button"
                      [disabled]="!canSaveAdr()"
                      (onClick)="saveAdr()"
                    />
                  </div>
                </form>
              }
          </section>
        }

        <!-- Workflows -->
        @if (draft()!.workflows.length > 0) {
          <section class="editor-section">
            <h3 class="section-title">
              Workflows
              <span class="count-badge">{{ draft()!.workflows.length }}</span>
            </h3>
            <div class="list-grid">
              @for (wf of draft()!.workflows; track wf.id; let i = $index) {
                <div class="list-card">
                    <input
                      pInputText
                      class="w-full card-input"
                      [value]="wf.name"
                      (blur)="onWorkflowChange(i, 'name', $any($event.target).value)"
                      placeholder="Workflow name"
                    />
                    <textarea
                      pTextarea
                      class="w-full"
                      rows="5"
                      [value]="wf.description"
                      (blur)="onWorkflowChange(i, 'description', $any($event.target).value)"
                      placeholder="Description"
                    ></textarea>
                    <div class="card-actions">
                      <p-button
                        label="Remove"
                        severity="danger"
                        [outlined]="true"
                        size="small"
                        (onClick)="removeItem('workflow', wf.id)"
                      />
                    </div>
                </div>
              }
            </div>
              <div class="section-footer">
                <p-button
                  label="Add Workflow"
                  icon="pi pi-plus"
                  severity="secondary"
                  [outlined]="true"
                  (onClick)="toggleAddForm('workflow')"
                />
              </div>
              @if (expandedAddForm() === 'workflow') {
                <form class="add-form">
                  <h4 class="add-form-title">New Workflow</h4>
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Workflow id (e.g. ship-flow)"
                    [(ngModel)]="newWorkflow.id"
                    name="workflowId"
                  />
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Name"
                    [(ngModel)]="newWorkflow.name"
                    name="workflowName"
                  />
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="3"
                    placeholder="Description"
                    [(ngModel)]="newWorkflow.description"
                    name="workflowDescription"
                  ></textarea>
                  <div class="add-form-actions">
                    <p-button
                      label="Cancel"
                      severity="secondary"
                      [text]="true"
                      type="button"
                      (onClick)="cancelAdd()"
                    />
                    <p-button
                      label="Save Workflow"
                      icon="pi pi-check"
                      type="button"
                      [disabled]="!canSaveWorkflow()"
                      (onClick)="saveWorkflow()"
                    />
                  </div>
                </form>
              }
          </section>
        }

        <!-- Agent Tasks -->
        @if (draft()!.agentTasks.length > 0) {
          <section class="editor-section">
            <h3 class="section-title">
              Agent Tasks
              <span class="count-badge">{{ draft()!.agentTasks.length }}</span>
            </h3>
            <div class="list-grid">
              @for (task of draft()!.agentTasks; track task.id; let i = $index) {
                <div class="list-card">
                    <input
                      pInputText
                      class="w-full card-input"
                      [value]="task.title"
                      (blur)="onTaskChange(i, 'title', $any($event.target).value)"
                      placeholder="Task title"
                    />
                    <textarea
                      pTextarea
                      class="w-full"
                      rows="5"
                      [value]="task.description"
                      (blur)="onTaskChange(i, 'description', $any($event.target).value)"
                      placeholder="Description"
                    ></textarea>
                    <div class="card-actions">
                      <p-button
                        label="Remove"
                        severity="danger"
                        [outlined]="true"
                        size="small"
                        (onClick)="removeItem('task', task.id)"
                      />
                    </div>
                </div>
              }
            </div>
              <div class="section-footer">
                <p-button
                  label="Add Task"
                  icon="pi pi-plus"
                  severity="secondary"
                  [outlined]="true"
                  (onClick)="toggleAddForm('task')"
                />
              </div>
              @if (expandedAddForm() === 'task') {
                <form class="add-form">
                  <h4 class="add-form-title">New Agent Task</h4>
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Task id (e.g. task-002)"
                    [(ngModel)]="newTask.id"
                    name="taskId"
                  />
                  <input
                    pInputText
                    class="w-full"
                    placeholder="Title"
                    [(ngModel)]="newTask.title"
                    name="taskTitle"
                  />
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="3"
                    placeholder="Description"
                    [(ngModel)]="newTask.description"
                    name="taskDescription"
                  ></textarea>
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="2"
                    placeholder="Acceptance criteria (one per line)"
                    [(ngModel)]="newTask.acceptanceCriteria"
                    name="taskAcceptance"
                  ></textarea>
                  <textarea
                    pTextarea
                    class="w-full"
                    rows="2"
                    placeholder="File hints (one per line)"
                    [(ngModel)]="newTask.fileHints"
                    name="taskHints"
                  ></textarea>
                  <div class="add-form-actions">
                    <p-button
                      label="Cancel"
                      severity="secondary"
                      [text]="true"
                      type="button"
                      (onClick)="cancelAdd()"
                    />
                    <p-button
                      label="Save Task"
                      icon="pi pi-check"
                      type="button"
                      [disabled]="!canSaveTask()"
                      (onClick)="saveTask()"
                    />
                  </div>
                </form>
              }
          </section>
        }

      </fieldset>
    }
  `,
  styles: `
    .empty-hint {
      color: var(--text-color-secondary);
      font-size: 0.9rem;
      padding: 2rem;
      text-align: center;
    }

    .fields-editor {
      border: 0;
      display: grid;
      gap: 2rem;
      margin: 0;
      padding: 0;
    }

    .editor-section {
      display: grid;
      gap: 1rem;
    }

    .section-title {
      align-items: center;
      border-bottom: 1px solid var(--surface-border);
      display: flex;
      font-size: 1rem;
      font-weight: 700;
      gap: 0.5rem;
      margin: 0;
      padding-bottom: 0.5rem;
    }

    .count-badge {
      background: var(--surface-200);
      border-radius: 9999px;
      color: var(--text-color-secondary);
      font-size: 0.7rem;
      font-weight: 600;
      padding: 0.1rem 0.45rem;
    }

    .field-grid {
      display: grid;
      gap: 0.75rem;
      grid-template-columns: 1fr 1fr;
    }

    .field {
      display: grid;
      gap: 0.3rem;
    }

    .full-width {
      grid-column: 1 / -1;
    }

    .field-label {
      color: var(--text-color-secondary);
      font-size: 0.8rem;
      font-weight: 500;
    }

    .field-hint {
      margin: 0;
      color: var(--text-color-secondary);
      font-size: 0.75rem;
    }

    .list-grid {
      display: grid;
      gap: 0.75rem;
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }

    .domains-list {
      grid-template-columns: minmax(0, 1fr);
    }

    .domains-list .list-card:has(textarea) {
      align-content: start;
    }

    .list-card {
      background: var(--surface-ground);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md, 8px);
      display: grid;
      gap: 0.5rem;
      min-width: 0;
      padding: 0.875rem;
    }

    .card-actions {
      align-items: center;
      display: flex;
      justify-content: flex-end;
    }

    .card-title-row {
      align-items: flex-start;
      display: flex;
      gap: 0.5rem;
      justify-content: space-between;
    }

    .card-title {
      font-size: 0.9rem;
      font-weight: 600;
      margin: 0;
    }

    .card-input {
      font-size: 0.9rem;
      font-weight: 600;
    }

    .card-text {
      color: var(--text-color-secondary);
      font-size: 0.85rem;
      line-height: 1.5;
      margin: 0;
    }

    .card-meta {
      color: var(--text-muted, var(--text-color-secondary));
      font-size: 0.75rem;
      margin: 0;
    }

    .section-footer {
      display: flex;
      flex-wrap: wrap;
      gap: 0.75rem;
      justify-content: flex-start;
    }

    .add-form {
      background: var(--surface-50);
      border: 1px dashed var(--surface-border);
      border-radius: var(--radius-md, 8px);
      display: grid;
      gap: 0.5rem;
      padding: 0.875rem;
    }

    .add-form-title {
      font-size: 0.85rem;
      font-weight: 600;
      margin: 0 0 0.25rem;
    }

    .add-form-actions {
      display: flex;
      gap: 0.5rem;
      justify-content: flex-end;
      margin-top: 0.25rem;
    }

    @media (max-width: 960px) {
      .list-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
    }

    @media (max-width: 640px) {
      .field-grid {
        grid-template-columns: 1fr;
      }

      .list-grid {
        grid-template-columns: minmax(0, 1fr);
      }
    }
  `,
})
export class PlanFieldsEditorComponent {

  protected readonly store = inject(ProjectStore);
  private readonly schema = inject(PlanSchemaService);

  protected readonly readonly = computed(() => this.store.isGenerating());

  protected readonly ideaDraft = computed(
    () => this.store.lastOriginalInput()?.idea ?? this.draft()?.meta?.userIdea ?? '',
  );

  protected readonly draft = signal<Plan | null>(null);

  protected readonly expandedAddForm = signal<AddFormKind | null>(null);

  protected newAdr: NewAdrDraft = { id: '', title: '', context: '', decision: '' };
  protected newWorkflow: NewWorkflowDraft = { id: '', name: '', description: '' };
  protected newTask: NewTaskDraft = {
    id: '',
    title: '',
    description: '',
    acceptanceCriteria: '',
    fileHints: '',
  };
  protected newDomainManual: NewDomainManualDraft = {
    name: '',
    description: '',
  };

  private lastGeneratedAt = '';

  constructor() {
    effect(
      () => {
        const plan = this.store.plan();
        if (!plan) return;
        if (plan.meta.generatedAt !== this.lastGeneratedAt) {
          this.lastGeneratedAt = plan.meta.generatedAt;
          this.draft.set(structuredClone(plan));
        }
      },
    );
  }

  protected onMetaChange(field: 'title' | 'summary', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const updated: Plan = { ...current, meta: { ...current.meta, [field]: value } };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected onUserIdeaChange(value: string): void {
    const current = this.draft();
    if (!current) return;
    const trimmed = value.trim();
    const currentIdea = current.meta.userIdea ?? '';
    if (trimmed === currentIdea) return;
    const updated: Plan = {
      ...current,
      meta: { ...current.meta, userIdea: trimmed || undefined },
    };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected onOverviewChange(field: 'purpose' | 'context', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const updated: Plan = {
      ...current,
      systemOverview: { ...current.systemOverview, [field]: value },
    };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected onDomainChange(index: number, field: 'name' | 'description', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const domains = current.domains.map((d, i) => (i === index ? { ...d, [field]: value } : d));
    const updated: Plan = { ...current, domains };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected isDomainStubbed(domainId: string): boolean {
    const plan = this.draft();
    if (!plan) return false;
    const domain = plan.domains.find((d) => d.id === domainId);
    return !!domain && domain.description.includes(STUB_MARKER);
  }

  protected onAdrChange(index: number, field: 'title' | 'decision', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const adrs = current.adrs.map((a, i) => (i === index ? { ...a, [field]: value } : a));
    const updated: Plan = { ...current, adrs };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected onWorkflowChange(index: number, field: 'name' | 'description', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const workflows = current.workflows.map((w, i) =>
      i === index ? { ...w, [field]: value } : w,
    );
    const updated: Plan = { ...current, workflows };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected onTaskChange(index: number, field: 'title' | 'description', value: string): void {
    const current = this.draft();
    if (!current || !value.trim()) return;
    const agentTasks = current.agentTasks.map((t, i) =>
      i === index ? { ...t, [field]: value } : t,
    );
    const updated: Plan = { ...current, agentTasks };
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  protected toggleAddForm(kind: AddFormKind): void {
    this.expandedAddForm.update((current) => (current === kind ? null : kind));
  }

  protected cancelAdd(): void {
    this.expandedAddForm.set(null);
  }

  protected canSaveAdr(): boolean {
    return Boolean(this.newAdr.id.trim() && this.newAdr.title.trim());
  }

  protected canSaveWorkflow(): boolean {
    return Boolean(this.newWorkflow.id.trim() && this.newWorkflow.name.trim());
  }

  protected canSaveTask(): boolean {
    return Boolean(
      this.newTask.id.trim() &&
        this.newTask.title.trim() &&
        this.newTask.acceptanceCriteria.trim() &&
        this.newTask.fileHints.trim(),
    );
  }

  protected canSaveDomainManual(): boolean {
    return Boolean(
      this.newDomainManual.name.trim() && this.newDomainManual.description.trim(),
    );
  }

  protected saveDomainManual(): void {
    const current = this.draft();
    if (!current || !this.canSaveDomainManual()) return;
    const name = this.newDomainManual.name.trim();
    const description = this.newDomainManual.description.trim();
    const id = this.slugify(name);
    if (!id) {
      this.store.setError({
        type: 'schema_validation',
        message: 'Domain name must contain at least one alphanumeric character.',
        fields: ['domains'],
      });
      return;
    }
    if (current.domains.some((d) => d.id === id)) {
      this.store.setError({
        type: 'schema_validation',
        message: `Domain "${name}" (id "${id}") already exists.`,
        fields: ['domains'],
      });
      return;
    }
    const layerId = current.architectureLayers[0]?.id ?? 'backend';
    const stub = this.schema.buildDomainStub(id, layerId);
    const domain: Domain = {
      ...stub,
      id,
      name,
      description,
    };
    const updated: Plan = { ...current, domains: [...current.domains, domain] };
    this.applyUpdate(updated);
    this.newDomainManual = {
      name: '',
      description: '',
    };
    this.expandedAddForm.set(null);
  }

  protected saveAdr(): void {
    const current = this.draft();
    if (!current || !this.canSaveAdr()) return;
    if (current.adrs.some((a) => a.id === this.newAdr.id.trim())) {
      this.store.setError({
        type: 'schema_validation',
        message: `ADR id "${this.newAdr.id.trim()}" already exists.`,
        fields: ['adrs'],
      });
      return;
    }
    const adr: Adr = {
      id: this.newAdr.id.trim(),
      title: this.newAdr.title.trim(),
      status: 'proposed',
      context: this.newAdr.context.trim() || 'TBD',
      decision: this.newAdr.decision.trim() || 'TBD',
      consequences: [],
    };
    const updated: Plan = { ...current, adrs: [...current.adrs, adr] };
    this.applyUpdate(updated);
    this.newAdr = { id: '', title: '', context: '', decision: '' };
    this.expandedAddForm.set(null);
  }

  protected saveWorkflow(): void {
    const current = this.draft();
    if (!current || !this.canSaveWorkflow()) return;
    if (current.workflows.some((w) => w.id === this.newWorkflow.id.trim())) {
      this.store.setError({
        type: 'schema_validation',
        message: `Workflow id "${this.newWorkflow.id.trim()}" already exists.`,
        fields: ['workflows'],
      });
      return;
    }
    const workflow: Workflow = {
      id: this.newWorkflow.id.trim(),
      name: this.newWorkflow.name.trim(),
      description: this.newWorkflow.description.trim() || 'TBD',
      steps: [],
      domainIds: [],
    };
    const updated: Plan = { ...current, workflows: [...current.workflows, workflow] };
    this.applyUpdate(updated);
    this.newWorkflow = { id: '', name: '', description: '' };
    this.expandedAddForm.set(null);
  }

  protected saveTask(): void {
    const current = this.draft();
    if (!current || !this.canSaveTask()) return;
    if (current.agentTasks.some((t) => t.id === this.newTask.id.trim())) {
      this.store.setError({
        type: 'schema_validation',
        message: `Task id "${this.newTask.id.trim()}" already exists.`,
        fields: ['agentTasks'],
      });
      return;
    }
    const task: AgentTask = {
      id: this.newTask.id.trim(),
      title: this.newTask.title.trim(),
      description: this.newTask.description.trim() || 'TBD',
      acceptanceCriteria: this.splitLines(this.newTask.acceptanceCriteria),
      fileHints: this.splitLines(this.newTask.fileHints),
      userStoryIds: [],
    };
    const updated: Plan = { ...current, agentTasks: [...current.agentTasks, task] };
    this.applyUpdate(updated);
    this.newTask = { id: '', title: '', description: '', acceptanceCriteria: '', fileHints: '' };
    this.expandedAddForm.set(null);
  }

  protected removeItem(kind: DomainKind, id: string): void {
    const current = this.draft();
    if (!current) return;
    const affectedPaths = this.markdownPathsForKind(kind, id);
    let updated: Plan;
    if (kind === 'adr') {
      updated = { ...current, adrs: current.adrs.filter((a) => a.id !== id) };
    } else if (kind === 'workflow') {
      updated = { ...current, workflows: current.workflows.filter((w) => w.id !== id) };
    } else if (kind === 'task') {
      updated = { ...current, agentTasks: current.agentTasks.filter((t) => t.id !== id) };
    } else {
      updated = { ...current, domains: current.domains.filter((d) => d.id !== id) };
    }
    this.applyUpdate(updated);
    if (affectedPaths.length > 0) {
      this.store.clearMarkdownOverrides(affectedPaths);
    }
  }

  protected markdownPathsForKind(kind: DomainKind, id: string): string[] {
    const current = this.draft();
    if (!current) return [];
    if (kind === 'adr') {
      const index = current.adrs.findIndex((a) => a.id === id);
      const adr = current.adrs.find((a) => a.id === id);
      if (index < 0 || !adr) return [];
      const slug = this.slugify(adr.title);
      return [`docs/20-decisions/adr-${String(index + 1).padStart(3, '0')}-${slug}.md`];
    }
    if (kind === 'workflow') {
      return [`docs/50-workflows/${id}.md`];
    }
    if (kind === 'domain') {
      const domain = current.domains.find((d) => d.id === id);
      if (!domain) return [];
      return this.domainMarkdownPaths({ id: domain.id, layer: domain.layer });
    }
    const index = current.agentTasks.findIndex((t) => t.id === id);
    const task = current.agentTasks.find((t) => t.id === id);
    if (index < 0 || !task) return [];
    const slug = this.slugify(task.title);
    return [
      `docs/60-agent-tasks/${String(index + 1).padStart(2, '0')}-${slug}.md`,
      'docs/60-agent-tasks/00-implementation-order.md',
    ];
  }

  private domainMarkdownPaths(domain: { id: string; layer: string }): string[] {
    const plan = this.store.plan();
    if (!plan) return [];
    const layers = plan.architectureLayers ?? [];
    let layerIndex = layers.findIndex((l) => l.id === domain.layer);
    if (layerIndex < 0) layerIndex = 0;
    const layerId = layers[layerIndex]?.id ?? domain.layer;
    const prefix = String((layerIndex + 1) * 10 + 20);
    return [`docs/10-architecture/${layerId}-architecture.md`, `docs/${prefix}-${layerId}/${domain.id}/overview.md`];
  }

  private applyUpdate(updated: Plan): void {
    this.draft.set(updated);
    this.store.replacePlanForUserEdit(updated);
  }

  private splitLines(value: string): string[] {
    return value
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0);
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
}
