import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  inject,
  signal,
} from '@angular/core';
import { ButtonModule } from 'primeng/button';
import { MessageModule } from 'primeng/message';
import { LLM_PROVIDERS } from '../../../core/llm-provider';
import { PdfCreatorService } from '../../../core/pdf-creator.service';
import { ProjectStore } from '../../../core/project.store';
import { exportBaseName } from '../../../core/feature-slug';
import { PdfDocumentRepair } from '../../../core/plan-schema.service';
import { ExportPdfButtonComponent } from './export-pdf-button.component';
import { ExportPdfStatsComponent } from './export-pdf-stats.component';

@Component({
  selector: 'app-export-pdf',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ButtonModule, MessageModule, ExportPdfButtonComponent, ExportPdfStatsComponent],
  template: `
    <section class="card export-shell" aria-labelledby="export-pdf-heading">
      <h3 id="export-pdf-heading">PDF</h3>
      <p class="subtitle">
        A rendered PDF version of the plan, generated by an LLM.
      </p>

      <app-export-pdf-stats
        [stats]="liveStats()"
        [active]="active()"
        [done]="done()"
        [durationLabel]="durationLabel()"
        [rateLabel]="rateLabel()"
        [etaLabel]="etaLabel()"
      />

      <div class="export-actions">
        <app-export-pdf-button
          [loading]="exportingPdf()"
          [disabled]="pdfButtonDisabled()"
          (click)="downloadPdf()"
        />
      </div>
      @if (pdfButtonDisabledReason(); as reason) {
        <p class="disabled-reason" data-testid="export-pdf-disabled-reason">{{ reason }}</p>
      }
      @if (lastRepair(); as r) {
        <p-message
          severity="warn"
          styleClass="w-full"
          data-testid="export-pdf-repair-warning"
          [text]="repairWarningText(r)"
        />
      }
      @if (lastPlaceholders() > 0) {
        <p-message
          severity="warn"
          styleClass="w-full"
          data-testid="export-pdf-placeholders-warning"
          [text]="placeholderWarningText()"
        />
      }
      @if (lastPreflightWarning(); as warn) {
        <p-message
          severity="info"
          styleClass="w-full"
          data-testid="export-pdf-preflight-warning"
          [text]="warn"
        />
      }
      @if (lastError(); as err) {
        <pre class="error-message" data-testid="export-pdf-error" role="alert"><strong>Export failed:</strong> {{ err }}</pre>
      }
    </section>
  `,
  styles: `
    .export-shell {
      display: grid;
      gap: 0.75rem;
      padding: 1rem;
    }

    .export-shell h3 {
      font-size: 1rem;
      font-weight: 600;
      margin: 0;
    }

    .subtitle {
      color: var(--text-color-secondary);
      font-size: 0.875rem;
      margin: 0;
    }

    .export-actions {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      margin-top: 0.5rem;
    }

    .disabled-reason {
      color: var(--text-color-secondary);
      font-size: 0.8125rem;
      margin: 0;
    }

    .error-message {
      color: var(--red-700, #b91c1c);
      background: var(--red-50, #fef2f2);
      border: 1px solid var(--red-200, #fecaca);
      border-radius: 4px;
      padding: 0.5rem 0.75rem;
      font-size: 0.8125rem;
      margin: 0;
      white-space: pre-wrap;
      font-family: inherit;
    }
  `,
})
export class ExportPdfComponent {
  protected readonly store = inject(ProjectStore);
  private readonly pdfCreator = inject(PdfCreatorService);

  protected readonly exportingPdf = signal(false);
  protected readonly lastError = signal<string | null>(null);
  protected readonly lastRepair = signal<PdfDocumentRepair | null>(null);
  protected readonly lastPlaceholders = signal<number>(0);
  protected readonly lastPreflightWarning = signal<string | null>(null);
  private readonly tick = signal(0);
  private tickHandle: ReturnType<typeof setInterval> | null = null;
  private readonly destroyRef = inject(DestroyRef);

  protected readonly hasPdfStats = computed(() => this.store.pdfTokenStats() !== null);

  protected readonly liveStats = computed(() => {
    this.tick();
    return this.store.pdfTokenStats();
  });

  protected readonly active = computed(
    () => this.store.isGenerating() && this.hasPdfStats(),
  );

  protected readonly pdfButtonDisabled = computed(() => {
    if (!this.store.plan()) return true;
    if (this.exportingPdf()) return true;
    const cfg = this.store.config();
    const slot = cfg.providerConfigs[cfg.provider];
    const descriptor = LLM_PROVIDERS[cfg.provider];
    if (!descriptor.requiresApiKey) return false;
    return !this.store.apiKey().trim() || !slot.selectedModel.trim();
  });

  protected readonly pdfButtonDisabledReason = computed<string | null>(() => {
    if (this.exportingPdf()) return null;
    if (!this.store.plan()) return 'No active plan. Generate or open a plan first.';
    const cfg = this.store.config();
    const slot = cfg.providerConfigs[cfg.provider];
    const descriptor = LLM_PROVIDERS[cfg.provider];
    if (descriptor.requiresApiKey) {
      const missing: string[] = [];
      if (!this.store.apiKey().trim()) missing.push(`${descriptor.apiKeyLabel}`);
      if (!slot.selectedModel.trim()) missing.push('a model');
      if (missing.length > 0) {
        return `Configure ${missing.join(' + ')} on the Config page to enable PDF export.`;
      }
    }
    return null;
  });

  protected readonly done = computed(
    () => !this.store.isGenerating() && this.store.pdfTokenStats() !== null,
  );

  protected readonly durationLabel = computed(() => {
    this.tick();
    const ts = this.store.pdfTokenStats();
    if (!ts?.startedAt) return '0s';
    const startedAtMs = new Date(ts.startedAt).getTime();
    const elapsedMs = Math.max(0, Date.now() - startedAtMs);
    return formatDuration(elapsedMs);
  });

  protected readonly rateLabel = computed(() => {
    this.tick();
    const ts = this.store.pdfTokenStats();
    if (!ts) return '0.0 tok/s';
    const startedAtMs = ts.startedAt ? new Date(ts.startedAt).getTime() : null;
    const durationMs = startedAtMs ? Math.max(0, Date.now() - startedAtMs) : 0;

    const chunkTs = this.pdfCreator.chunkTimestamps();
    const now = Date.now();
    const cutoff = now - 5_000;
    const recent = chunkTs.filter((t) => t >= cutoff);
    let rate: number;
    if (recent.length >= 2) {
      const span = Math.max(1, recent[recent.length - 1] - recent[0]);
      rate = ((recent.length - 1) / span) * 1000;
    } else {
      const elapsedSeconds = durationMs / 1000 || 1;
      rate = ts.completionTokens / elapsedSeconds;
    }

    if (!Number.isFinite(rate) || rate <= 0) return '0.0 tok/s';
    return `${rate.toFixed(1)} tok/s`;
  });

  protected readonly etaLabel = computed<string | null>(() => {
    this.tick();
    const ts = this.store.pdfTokenStats();
    if (!ts || !ts.startedAt) return null;
    const startedAtMs = new Date(ts.startedAt).getTime();
    const durationMs = Math.max(0, Date.now() - startedAtMs);

    const chunkTs = this.pdfCreator.chunkTimestamps();
    const now = Date.now();
    const cutoff = now - 5_000;
    const recent = chunkTs.filter((t) => t >= cutoff);
    let rate: number;
    if (recent.length >= 2) {
      const span = Math.max(1, recent[recent.length - 1] - recent[0]);
      rate = ((recent.length - 1) / span) * 1000;
    } else {
      const elapsedSeconds = durationMs / 1000 || 1;
      rate = ts.completionTokens / elapsedSeconds;
    }

    if (!Number.isFinite(rate) || rate <= 0.05 || ts.completionTokens <= 0) return null;
    const seconds = Math.round(ts.completionTokens / rate);
    if (!Number.isFinite(seconds) || seconds < 0) return null;
    return formatDuration(seconds * 1000);
  });

  constructor() {
    effect(() => {
      const active = this.exportingPdf() && this.store.isGenerating();
      if (active) {
        this.startTicking();
      } else {
        this.stopTicking();
      }
    });

    this.destroyRef.onDestroy(() => this.stopTicking());
  }

  protected downloadPdf = async (): Promise<void> => {
    const plan = this.store.plan();
    if (!plan || this.exportingPdf() || this.pdfButtonDisabled()) return;
    this.exportingPdf.set(true);
    this.lastError.set(null);
    this.lastRepair.set(null);
    this.lastPlaceholders.set(0);
    this.lastPreflightWarning.set(null);
    try {
      const result = await this.pdfCreator.generate(plan);
      if (result.ok) {
        if (result.repair) {
          this.lastRepair.set(result.repair);
        }
        if (result.placeholders > 0) {
          this.lastPlaceholders.set(result.placeholders);
        }
        if (result.preflightWarning) {
          this.lastPreflightWarning.set(result.preflightWarning);
        }
        triggerDownload(result.blob, `${exportBaseName(plan)}-spec.pdf`);
        clearPdfExportReloadFlag();
      } else {
        this.lastError.set(stripViteCacheUrl(result.error.message));
        if (result.preflightWarning) {
          this.lastPreflightWarning.set(result.preflightWarning);
        }
      }
    } catch (e) {
      if (isPdfExportReloadError(e)) {
        this.lastError.set(
          'Dev server cache is stale and could not be refreshed automatically. ' +
            'Stop the dev server, delete the .angular/cache folder, then run npm start again.',
        );
      } else {
        this.lastError.set(stripViteCacheUrl(errorMessage(e)));
      }
    } finally {
      this.exportingPdf.set(false);
    }
  };

  private startTicking(): void {
    this.stopTicking();
    this.tickHandle = setInterval(() => {
      this.tick.update((n) => n + 1);
    }, 100);
  }

  protected placeholderWarningText(): string {
    const n = this.lastPlaceholders();
    const noun = n === 1 ? 'section is' : 'sections are';
    return `PDF generated with ${n} placeholder ${noun} because one or more per-section LLM calls failed twice. Re-run the export — failed sections will be retried with a different shard of the plan.`;
  }

  protected repairWarningText(repair: PdfDocumentRepair): string {
    const noun = repair.placeholderCount === 1 ? 'placeholder section' : 'placeholder sections';
    const reasonSentence =
      repair.reason === 'single_section_root'
        ? 'the LLM emitted a single section instead of a full document.'
        : repair.reason === 'array_section_headings'
          ? 'the LLM emitted only the section headings, without body content.'
          : repair.reason === 'matrix_shape'
            ? 'one or more matrix blocks had row/cell counts that did not match the column count — missing cells were filled with empty strings and over-long rows were trimmed.'
            : 'the LLM response was truncated or schema-drifted.';
    const diagnostics: string[] = [];
    if (typeof repair.rawBytes === 'number') {
      diagnostics.push(`${repair.rawBytes.toLocaleString()} chars`);
    }
    if (repair.finishReason) {
      diagnostics.push(`finish_reason="${repair.finishReason}"`);
    }
    if (typeof repair.attemptCount === 'number') {
      diagnostics.push(`${repair.attemptCount} attempt(s)`);
    }
    const detail = diagnostics.length > 0 ? ` (${diagnostics.join(', ')})` : '';
    const next =
      repair.reason === 'single_section_root' ||
      repair.reason === 'array_section_headings' ||
      repair.reason === 'matrix_shape'
        ? 'Re-run the export — the next attempt now includes a targeted hint to the LLM for this exact shape.'
        : 'Re-run with a higher max_tokens in Config (≥ 32 000 recommended) or split the plan into smaller pieces.';
    return (
      `PDF generated with ${repair.placeholderCount} ${noun} because ${reasonSentence}${detail}. ${next}`
    );
  }

  private stopTicking(): void {
    if (this.tickHandle !== null) {
      clearInterval(this.tickHandle);
      this.tickHandle = null;
    }
  }
}

function formatDuration(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return '0s';
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  if (minutes === 0) return `${seconds}s`;
  return `${minutes}m ${seconds}s`;
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  // Defer the revoke so Safari has a chance to read the blob.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

const VITE_DEPS_URL_RE = /\.angular\/cache\/[^?\s]*\/vite\/deps\/[^?\s]*\?v=[^\s)]*/;

function stripViteCacheUrl(message: string): string {
  return message.replace(VITE_DEPS_URL_RE, '[dev-server cache url]');
}

function isPdfExportReloadError(e: unknown): boolean {
  if (e instanceof Error && e.name === 'PdfExportReloadRequested') return true;
  if (e && typeof e === 'object' && (e as { isReload?: unknown }).isReload === true) {
    return true;
  }
  return false;
}

function errorMessage(e: unknown): string {
  return e instanceof Error ? e.message : 'Unexpected PDF generation failure.';
}

function clearPdfExportReloadFlag(): void {
  if (typeof sessionStorage !== 'undefined') {
    sessionStorage.removeItem('pdf-export-reload-requested');
  }
}
